[package]
name = "ammaccare"
version = "0.1.0"
authors = ["Sam Scott <sam.scott89@gmail.com>"]

[dependencies]
sodiumoxide = "0.2.0"
failure = "0.1.3"
url = "1.7.2"
serde = "1.0.82"
serde_derive = "1.0.82"
data-encoding = "2.1.1"
